---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
card_base <- read_csv("data/CardBase.csv")
customer_base <- read_csv("data/CustomerBase.csv")
exam_scores <- read_csv("data/exam_scores.csv")
fraud_base <- read_csv("data/FraudBase.csv")
hat_observations <- read_csv("data/hat_observations.csv")
transaction_base <- read_csv("data/TransactionBase.csv")
```

1. 
```{r}
card_base <- janitor::clean_names(card_base)
customer_base <- janitor::clean_names(customer_base)
fraud_base <- janitor::clean_names(fraud_base)
transaction_base <- janitor::clean_names(transaction_base)


card_base
customer_base
```


2.
```{r}
card_customer_base <- left_join(card_base, customer_base, by = "cust_id")

card_customer_base
```

3.
```{r}
full_join(fraud_base, transaction_base)
```

Mutating Joins
Inner, Left, Right - go and fetch extra columns (and rows?!) from foreign table

"Filitering Joins"
Semi, Anti - filter your "home" table by a foriegn criteriaa


4.
```{r}
card_base
transaction_base




semi_join(card_base, transaction_base, by = c("card_number" = "credit_card_id"))
```




5.
```{r}
hat_observations <- hat_observations %>% 
  separate(observation, c("hat_colour", "hat_type"),
           sep = ",")

hat_observations
  
```

6. 
```{r}
hat_observations <- hat_observations %>% 
  unite('date', c('year', 'month', 'day'),
                sep = "-")

hat_observations
```


EXTENSION:


1.
```{r}
card_base %>% 
  inner_join(customer_base, by = "cust_id") %>% 
  inner_join(transaction_base, by = c("card_number" = "credit_card_id")) %>% 
  inner_join(fraud_base, by = "transaction_id")
```


2. 
```{r}
exam_scores_edited <- exam_scores %>% 
  pivot_longer(starts_with("exam"),
               names_to = "exam_question",
               values_to = "score")
  
exam_scores_separate <- exam_scores_edited %>%
  separate(exam_question, c("blank", "exam_question"),
         sep = "exam_Q") %>% 
  select(-"blank") %>% 
  mutate(exam_question = as.numeric(exam_question))

exam_scores_separate
```




