---
title: "Day 3 HW"
output: html_notebook
---

1.
```{r}
library(tidyverse)
library(infer)
library(janitor)

ames <- read_csv("data/ames.csv") %>% 
  clean_names()
```


2.
```{r}
ggplot(ames) +
  aes(x = lot_area) +
  geom_histogram()
```

There is some very expensive outliers heavily skewing the data right.

3.
```{r}
x <- ames %>% 
  rep_sample_n(size = 200, reps = 1000, replace = TRUE) %>% 
  summarise(
    sampling_mean = mean(lot_area)
  )

ggplot(x) +
  aes(x = sampling_mean) +
  geom_histogram()
```


4.
```{r}
ci95 <- x %>% 
  get_ci(level = 0.95, type = "percentile")

lower95 <- ci95$lower_ci
upper95 <- ci95$upper_ci


ggplot(x) +
  aes(x = sampling_mean) +
  geom_histogram() +
  geom_vline(xintercept = lower95) +
  geom_vline(xintercept = upper95)
```


5.
```{r}
ci99 <- x %>% 
  get_ci(level = 0.99, type = "percentile")

lower99 <- ci99$lower_ci
upper99 <- ci99$upper_ci


ggplot(x) +
  aes(x = sampling_mean) +
  geom_histogram() +
  geom_vline(xintercept = lower99) +
  geom_vline(xintercept = upper99)

ci99
ci95
```

99% is a broader range which makes sense, as a bigger margin of error is necessary to be 99% sure.


```{r}
x %>% 
  summarise(point_estimate = mean(sampling_mean))
```




